REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.EntityContr TO operator;
REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.IndividContr TO operator;
REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.Goods TO operator;
REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.UserRoles TO operator;
REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.Books TO operator;
REVOKE INSERT, UPDATE, DELETE, REFERENCES, ALTER ON Sklyar_A.DocTypes TO operator;
REVOKE DELETE, REFERENCES, ALTER ON Sklyar_A.Documentation TO operator;
REVOKE DELETE, REFERENCES, ALTER ON Sklyar_A.GoodsMoves TO operator;